```{r global_options, include=FALSE, echo = FALSE, message = FALSE}
library(ggplot2)
library(mapdata)
library(maps)

knitr::opts_chunk$set(fig.width=12, fig.height=8, 
                      echo=FALSE, warning=FALSE, message=FALSE)

opts_knit$set(upload.fun = image_uri)

```
# Summary report for: `r spp_summ$spp_name`


## Overview of BBS data

Number of routes: `r spp_summ$n.routes`  

Number of outliers: `r spp_summ$n.outliers`

Number of buffered routes: `r spp_summ$n.buffer`

```{r route_map, echo = FALSE, message = FALSE, fig.width = 12, fig.height = 10}
BBSclim::PlotRoutes("lowa")

```

## Results

Annual variation in $p$: **`r spp_summ$annual`**


## $\psi$ maps
```{r psi_map, echo = FALSE, message = FALSE}
BBSclim::MapPsi(alpha = spp_summ$spp_alpha)
```

```{r lat_indices, echo = FALSE, message = FALSE}
BBSclim::PlotLat(alpha = spp_summ$spp_alpha)
```

## AIC Tables
### Annual variation AIC table
```{r annual_results, echo=FALSE, comment='', results='asis'}
kable(spp_summ$annual.aic, "markdown", align="c", padding=2)
```

### $\psi$ models
```{r psi_results, echo=FALSE, comment='', results='asis'}
kable(spp_summ$psi.aic[1:max(which(!is.na(spp_summ$psi.aic$LogLik))), -1], "markdown", align="c", padding=2)
```

### $\gamma$/$\epsilon$ models
```{r gam_results, echo=FALSE, comment='', results='asis'}
kable(spp_summ$gam.aic[1:max(which(!is.na(spp_summ$gam.aic$LogLik))), -1], "markdown", align="c", padding=2)
```

## $\beta$ estimates
### $\psi$, $\gamma$, & $\epsilon$
```{r betas, echo=FALSE, comment='', results='asis'}
kable(spp_summ$psi.betas, "markdown", align="c", padding=2)
```

### $\theta$, $\theta'$, $p$ & $\omega$
```{r betas2, echo=FALSE, comment='', results='asis'}
kable(spp_summ$p.betas, "markdown", align="c", padding=2)
```
